### PR TITLE
Answers to quiz

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by srhoulam** [comment]
SQL syntax is good. You've got your commands right, got your semicolons, but had trouble escaping quotes in strings. If there's an apostrophe in a string, you want to precede it with a blackslash, like so:

`SELECT * FROM people WHERE age > 40 OR title = 'Lord Commander of the Night\'s Watch';`

It will otherwise throw a syntax error.

**Comment by srhoulam** [comment]
Disregard that last part, your escaping is good. Doubling apostrophes is how you escape them with Postgres.

**Comment by srhoulam** [comment]
6/6

**Comment by ghost** [comment]
Thanks for reviewing my assessment, Saad!

**Pull request closed without merging**
