### PR TITLE
Complete SQL Diagnostic

### PR DESCRIPTION
**Pull request by kmg1434**
Clarity: 4   (is this supposed to be clarity of instructions?)
Comfort: 4

I used yesterdays SQL training and technonthenet.com for reference

### CODE REVIEW

**Comment by BenGitsCode** [comment]
@kmg1434 It should be your personal sense of comfort/clarity with the material at hand. Feel free to include any notes on the instructions or open an issue about them.

**Review by BenGitsCode — COMMENTED** [review]
5/5

good job! 👍

**Comment by kmg1434** [comment]
But if the material is clear to me wouldn't I be comfortable with it? And if I'm comfortable with the material wouldn't it be clear to me? I'm confused as to what the difference is.

**Comment by BenGitsCode** [comment]
You can have an unclear understanding of a concept after reading perfectly clear instructions. 

The difference is one is your personal sense of understanding—did you know the answers? Did they make sense to you? (high clarity) Did you get the right answers after research and feel uneasy with your answer? Did you just copy and paste things that happened to work? (low clarity)—and the other is a mix of subjective and objective perceptions. Does that make any sense?

In this context, clarity is always referencing how clearly you think you understand the relevant concepts.

**Comment by BenGitsCode** [comment]
You can have an unclear understanding of a concept after reading perfectly clear instructions. 

The difference is one is your personal sense of understanding—did you know the answers? Did they make sense to you? (high clarity) Did you get the right answers after research and feel uneasy with your answer? Did you just copy and paste things that happened to work? (low clarity)—and the other is a mix of subjective and objective perceptions. Does that make any sense?

In this context, clarity is always referencing how clearly you think you understand the relevant concepts.

**Pull request closed without merging**
